name: Reusable Workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: There is no description
        required: false
        default: dist
        type: string

jobs:
  printing:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Artifacts
        uses: actions/download-artifact@v2.1.1
        with:
          name: ${{inputs.artifact-name}}
      - name: Printing the artifacts we got from parent workflow
        uses: ls
      - name: Printing the output
        run: echo "If This output is getting showed means a workflow is made reusable and used in this workflow"
